# Generated by Django 3.0.5 on 2020-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
