# Generated by Django 3.0.5 on 2020-12-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20201219_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
