# Generated by Django 3.0.5 on 2020-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_auto_20201221_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items_order',
            field=models.ManyToManyField(to='lib.Orderitem'),
        ),
    ]
