# Generated by Django 3.0.5 on 2020-12-25 09:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0012_auto_20201221_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='city',
            new_name='address2',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='state',
        ),
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='payment',
            field=models.CharField(choices=[('E', 'eSewa'), ('K', 'Khalti')], max_length=200, null=True),
        ),
    ]
