# Generated by Django 3.0.5 on 2020-12-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0013_auto_20201225_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
